### PR TITLE
Port to MacOS, Compiler warnings removed, thus found many errors.

### PR DESCRIPTION
**Pull request by dl1ycf**
Includes two fixes for STEMlab/HAMlab.

Dear John, there are *many* changes. Most of them just were necessary to remove compiler warnings, such as non-void functions returning no value, etc. In this procedure, also some critical errors were found. I marked all changes with // DL1YCF comments. The trivial ones such as "returned a value to make the compiler happy" should be removed upon merging. They are intended to help you on deciding whether to accept or reject the suggested change.

So you see, take your time to consider all this.

### CODE REVIEW

**Comment by g0orx** [comment]
I have just merged the changes.

Thanks

-- John

**Comment by dl1ycf** [comment]
> Am 08.06.2018 um 12:38 schrieb John Melton <notifications@github.com>:
> 
> I have just merged the changes.
> 
> Thanks
> 
> — John


Great. Perhaps you might want to try it on your MacMini.

BTW, the Makefile is now with the options activated for a Macintosh,
perhaps one should change this back to have „Raspberry with GPIO“
as the default?

Yours,

Christoph DL1YCF.

**Comment by g0orx** [comment]
I am away in Mallorca for a week so will try it when I get home.

Thanks for your work on this.

John

**Comment by dl1ycf** [comment]
Dear John,

this weekend I did on-the-air testing with my RedPitaya SDR, piHPSDR running on
MacOS, virtual audio cables and wsjtx as a digimode program. On 17m I had some
problems with the SDR not transmitting, with an „out of band“ error message.

The reason is as follows:

in frequency.c, it is required that the whole TX channel is within a
specific *sub* - band. Now in my setup wsjtx is configured that it
switches the TX frequency from 18100 kHz to 18099 kHz if the audio
is on the low end, e.g. 800 Hz. This is the best setup at least
for analog radios, it takes care that the harmonics of the audio 
signal fall outside the passband.
The problem is now, that there is no „band“ in frequency.c that
covers the range 18099 to 18102 kHz, which is the nominal freq
range of the USB signal on 17m WSJTX for the lower AF frequencies.

One might be tempted to to add a line to the freqinfo data set,
as to have a „band“ that covers the entire 17m band and which is
selected if nothing else fits. But this
does not work since in getFrequencyInfo, the search stops
as soon as the lower edge of the TX signal is lower than the
lower edge of the current sub-band:

        if(flow<info->minFrequency) {
            info=0;
            break;


My question now is: should piHPSDR be changed such that
TX signals completely *within* a ham band, but crossing
a sub-band border, are allowed? If the answer is „yes“
I can certainly change frequency.c as to allow this.

The next thing is, that hamlib does not work correctly
with piHPSDR. I meanwhile have changed this in hamlib,
that is, I take your implementation of rigctl in piHPSDR
as the „gold standard“ and change hamlib such that the
two work together. The two issues are:

- piHPSDR hijacks two RTTY modes when it „means“
  USB-DATA and LSB-DATA. PowerSDR and other programs behave in
  exactly the same way, so hamlib already has a hook for this,
  which needs be activated in the piHPSDR case.
  Then, if hamlib changes the mode to PKTUSB piHPSDR goes DIGU,
  and if piHPSDR is in DIGU mode, hamlib reports PKTUSB. This is
  almost certainly what is intended.

- When setting the RF Power output, hamlib does the
  conversion the wrong way. It maps the input values between
  0.0 and 1.0 to integer values between 0 and 255 for the
  PC command, but the leagal range, as defined by your
  rigctl.c, is 0 to 100. Note that when *reading* the RF power,
  hamlib already does the conversion correctly. It is a one-line
  change to fix this.

What I want to hear from you is simply that your rigctl
implementation stands at it is, then I can issue a pull
request for hamlib. The reason simply is, that there are
two options here: change hamlib such that it works with
piHPSDR (my suggestion), or change piHPSDR such that it
works with hamlib (not quite logical).

Yours,

**Pull request merged**
